# Creat by Abraão Silva
# Date 12 Nov 2018 
version: '3'
services:
  jfrog-artifactory:
    container_name: jfrog-artifactory
    image: docker.bintray.io/jfrog/artifactory-oss
    volumes:
      - "$PWD/artifactory-data/data:/opt/jfrog/artifactory/data"
      - "$PWD/artifactory-data/logs:/opt/jfrog/artifactory/logs"
      - "$PWD/artifactory-data/backup:/opt/jfrog/artifactory/backup"
      - "$PWD/artifactory-data/etc:/opt/jfrog/artifactory/etc"
    restart: always
    command: --acme-domain artifactory.s4bdigital.net
# environment:
#    - EXTRA_JAVA_OPTIONS=-Xmx4g
    ports:
     - "80:8081"
#     - "443:443"
#     - '5005:5005'
#     - '5006:5006'
#     - '5007:5007'

